server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/audit_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://keycloak:8080/realms/112}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://keycloak:8080/realms/112/protocol/openid-connect/certs}

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml
