global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: spring-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - gateway-service:8080
          - auth-service:8081
          - incident-service:8082
          - dispatch-service:8083
          - telephony-service:8084
          - gis-service:8085
          - audit-service:8086
          - notification-service:8087
          - realtime-service:8088
        labels:
          system: emergency-112
  - job_name: ai-service
    metrics_path: /metrics
    static_configs:
      - targets: ["ai-service:8090"]
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
