{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "e112.fullname" . }}
  labels:
    {{- include "e112.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.hosts.dispatcher | quote }}
        - {{ .Values.ingress.hosts.api | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hosts.api | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: {{ (index .Values.services "gateway-service").port }}
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: {{ (index .Values.services "gateway-service").port }}
    - host: {{ .Values.ingress.hosts.dispatcher | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-dispatcher
                port:
                  number: {{ (index .Values.services "frontend-dispatcher").port }}
{{- end }}
