apiVersion: v1
kind: Secret
metadata:
  name: {{ include "e112.fullname" . }}-secrets
  labels:
    {{- include "e112.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  KEYCLOAK_ADMIN_USER: {{ .Values.secrets.keycloakAdminUser | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secrets.keycloakAdminPassword | quote }}
