replicaCount: 1
image:
  repository: auth-service
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
env:
  spring_profiles_active: "prod"
  spring_security_oauth2_resourceserver_jwt_issuer_uri: "http://keycloak:8080/realms/112"
  spring_security_oauth2_resourceserver_jwt_jwk_set_uri: "http://keycloak:8080/realms/112/protocol/openid-connect/certs"
