replicaCount: 1

image:
  repository: registry.example.com/112/incident-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

resources: {}

env:
  spring_profiles_active: "prod"
  spring_security_oauth2_resourceserver_jwt_issuer_uri: "http://keycloak:8080/realms/112"
  spring_security_oauth2_resourceserver_jwt_jwk_set_uri: "http://keycloak:8080/realms/112/protocol/openid-connect/certs"
  spring_security_oauth2_resourceserver_jwt_audiences: "incident-service"
